// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Infrastructure.Persistence;

#nullable disable

namespace TMS.Infrastructure.Migrations
{
    [DbContext(typeof(TMSDbContext))]
    partial class TMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("TMS.Domain.Entities.Companies.Carrier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DOT_Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MC_Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("TMS.Domain.Entities.ComplianceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("ComplianceDocuments");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LoadId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Drivers.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CDLExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CDLNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Drivers.DriverAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AcceptanceRate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedTractorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedTrailerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AvailableFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AvailableUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedLoadsCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursWorkedThisWeek")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursWorkedToday")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLocationUpdate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OnTimeDeliveryRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverAvailabilities");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Equipment.PowerOnlyTractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentMileage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FuelCapacity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.ToTable("PowerOnlyTractors");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.CheckCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETA")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTruckEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrailerTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId");

                    b.ToTable("CheckCalls");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.Dispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AvailabilityScore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PerformanceScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProximityScore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TractorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrailerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId");

                    b.HasIndex("TractorId");

                    b.HasIndex("TrailerId");

                    b.ToTable("Dispatches");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.Load", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AccessorialCharges")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveryDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FuelSurcharge")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoadNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LoadType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PickupDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProofOfDeliveryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TractorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrailerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("DriverId");

                    b.HasIndex("ProofOfDeliveryId");

                    b.HasIndex("TractorId");

                    b.HasIndex("TrailerId");

                    b.ToTable("Loads");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.PODPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 12, 17, 22, 14, 31, 570, DateTimeKind.Utc).AddTicks(3922));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProofOfDeliveryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProofOfDeliveryId");

                    b.ToTable("PODPhotos");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.ProofOfDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveryDateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DeliveryLatitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DeliveryLongitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedDeliveryDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsOnTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureData")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId")
                        .IsUnique();

                    b.HasIndex("TripId");

                    b.ToTable("ProofsOfDelivery");
                });

            modelBuilder.Entity("TMS.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Notes.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisibleToCustomer")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentNoteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsPinned");

                    b.HasIndex("ParentNoteId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Tracking.DriverLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Accuracy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DispatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Heading")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpeedMph")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DispatchId");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverLocations");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Tracking.GeofenceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AlertedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DispatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverLocationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DispatchId");

                    b.HasIndex("DriverLocationId");

                    b.ToTable("GeofenceAlerts");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Trailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AxleCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrailerNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trailers");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FuelGallonsUsed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalMiles")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TractorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LoadId");

                    b.HasIndex("TractorId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Companies.Carrier", b =>
                {
                    b.OwnsOne("TMS.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CarrierId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CarrierId");

                            b1.ToTable("Carriers");

                            b1.WithOwner()
                                .HasForeignKey("CarrierId");
                        });

                    b.OwnsOne("TMS.Domain.Entities.Companies.InsuranceInfo", "InsuranceInfo", b1 =>
                        {
                            b1.Property<Guid>("CarrierId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CoverageAmount")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("ExpiryDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PolicyNumber")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CarrierId");

                            b1.ToTable("Carriers");

                            b1.WithOwner()
                                .HasForeignKey("CarrierId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("InsuranceInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TMS.Domain.Entities.ComplianceDocument", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Drivers.Driver", "Driver")
                        .WithMany("ComplianceDocuments")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Document", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("TMS.Domain.Entities.Loads.Load", "Load")
                        .WithMany("Documents")
                        .HasForeignKey("LoadId");

                    b.Navigation("Driver");

                    b.Navigation("Load");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Drivers.Driver", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Companies.Carrier", "Carrier")
                        .WithMany("Drivers")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TMS.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("DriverId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("DriverId");

                            b1.ToTable("Drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Drivers.DriverAvailability", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TMS.Domain.ValueObjects.Address", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("DriverAvailabilityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("DriverAvailabilityId");

                            b1.ToTable("DriverAvailabilities");

                            b1.WithOwner()
                                .HasForeignKey("DriverAvailabilityId");
                        });

                    b.Navigation("CurrentLocation");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Equipment.PowerOnlyTractor", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Companies.Carrier", "Carrier")
                        .WithMany("Equipment")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.CheckCall", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Drivers.Driver", "Driver")
                        .WithMany("CheckCalls")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS.Domain.Entities.Loads.Load", "Load")
                        .WithMany("CheckCalls")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Load");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.Dispatch", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS.Domain.Entities.Loads.Load", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS.Domain.Entities.Equipment.PowerOnlyTractor", "Tractor")
                        .WithMany()
                        .HasForeignKey("TractorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TMS.Domain.Entities.Trailer", "Trailer")
                        .WithMany()
                        .HasForeignKey("TrailerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Driver");

                    b.Navigation("Load");

                    b.Navigation("Tractor");

                    b.Navigation("Trailer");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.Load", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Companies.Carrier", "Carrier")
                        .WithMany("Loads")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS.Domain.Entities.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("TMS.Domain.Entities.Loads.ProofOfDelivery", "ProofOfDelivery")
                        .WithMany()
                        .HasForeignKey("ProofOfDeliveryId");

                    b.HasOne("TMS.Domain.Entities.Equipment.PowerOnlyTractor", "Tractor")
                        .WithMany()
                        .HasForeignKey("TractorId");

                    b.HasOne("TMS.Domain.Entities.Trailer", "Trailer")
                        .WithMany("Loads")
                        .HasForeignKey("TrailerId");

                    b.OwnsOne("TMS.Domain.ValueObjects.Address", "DeliveryLocation", b1 =>
                        {
                            b1.Property<Guid>("LoadId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("LoadId");

                            b1.ToTable("Loads");

                            b1.WithOwner()
                                .HasForeignKey("LoadId");
                        });

                    b.OwnsOne("TMS.Domain.ValueObjects.Address", "PickupLocation", b1 =>
                        {
                            b1.Property<Guid>("LoadId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("LoadId");

                            b1.ToTable("Loads");

                            b1.WithOwner()
                                .HasForeignKey("LoadId");
                        });

                    b.Navigation("Carrier");

                    b.Navigation("DeliveryLocation")
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("PickupLocation")
                        .IsRequired();

                    b.Navigation("ProofOfDelivery");

                    b.Navigation("Tractor");

                    b.Navigation("Trailer");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.PODPhoto", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Loads.ProofOfDelivery", "ProofOfDelivery")
                        .WithMany("Photos")
                        .HasForeignKey("ProofOfDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProofOfDelivery");
                });

            modelBuilder.Entity("TMS.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Equipment.PowerOnlyTractor", "Equipment")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Notes.Note", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Notes.Note", "ParentNote")
                        .WithMany("Replies")
                        .HasForeignKey("ParentNoteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentNote");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Tracking.DriverLocation", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Loads.Dispatch", "Dispatch")
                        .WithMany()
                        .HasForeignKey("DispatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TMS.Domain.Entities.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispatch");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Tracking.GeofenceAlert", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Loads.Dispatch", "Dispatch")
                        .WithMany()
                        .HasForeignKey("DispatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS.Domain.Entities.Tracking.DriverLocation", "DriverLocation")
                        .WithMany()
                        .HasForeignKey("DriverLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispatch");

                    b.Navigation("DriverLocation");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Trips.Trip", b =>
                {
                    b.HasOne("TMS.Domain.Entities.Drivers.Driver", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS.Domain.Entities.Loads.Load", "Load")
                        .WithMany("Trips")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS.Domain.Entities.Equipment.PowerOnlyTractor", "Tractor")
                        .WithMany("Trips")
                        .HasForeignKey("TractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Load");

                    b.Navigation("Tractor");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Companies.Carrier", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Equipment");

                    b.Navigation("Loads");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Drivers.Driver", b =>
                {
                    b.Navigation("CheckCalls");

                    b.Navigation("ComplianceDocuments");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Equipment.PowerOnlyTractor", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.Load", b =>
                {
                    b.Navigation("CheckCalls");

                    b.Navigation("Documents");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Loads.ProofOfDelivery", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Notes.Note", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TMS.Domain.Entities.Trailer", b =>
                {
                    b.Navigation("Loads");
                });
#pragma warning restore 612, 618
        }
    }
}
